[grid]
dim = [50, 50, 1]
sublattices = 2
spin_magnitudes = [1.5, 1.5]
pbc = [true, true, false]

[simulation]
initial_state = "z"
model = "ising"       
n_equil = 100000      
n_steps = 100000
# 手动指定温度列表（二选一，优先使用）
# temperatures = []
# 如果不写temperatures，则用下面区间自动生成
temp_start = 41
temp_end = 80
temp_step = 1

num_threads = 20

[output]
outfile = "result.txt"

[[exchange]]
from_sub = 0
to_sub = 1
offsets = [[0, 0, 0], [1, 0, 0], [0, 1, 0]]
strength = 0.0013548


[[exchange]]
from_sub = 1
to_sub = 0
offsets = [[0, 0, 0], [-1, 0, 0], [0, -1, 0]]
strength = 0.0013548


